# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_rarefaction <- function(input, rMatrix, inColNames, inRowNames, repeats, depth, seed, NoOfMatrices, verbose = FALSE, threads = 1L, margin = 2L, tmpDir = "", lowmem = FALSE) {
    .Call(`_rtk_rcpp_rarefaction`, input, rMatrix, inColNames, inRowNames, repeats, depth, seed, NoOfMatrices, verbose, threads, margin, tmpDir, lowmem)
}

