# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_rarefaction <- function(input, output, rMatrix, inColNames, inRowNames, repeats, rareDepth, NoOfMatrices, verbose = FALSE, returnObject = FALSE, margin = 1L) {
    .Call('rarefaction_rcpp_rarefaction', PACKAGE = 'rarefaction', input, output, rMatrix, inColNames, inRowNames, repeats, rareDepth, NoOfMatrices, verbose, returnObject, margin)
}

